TICKER_SECTOR_MAP = {
    # === B3 - BRASIL ===
    # Energia / Commodities
    "PETR4.SA": "ENERGIA",
    "PETR3.SA": "ENERGIA",
    "PRIO3.SA": "ENERGIA",
    "UGPA3.SA": "ENERGIA",
    "VALE3.SA": "MINERACAO",
    "CSNA3.SA": "SIDERURGIA",
    "GGBR4.SA": "SIDERURGIA",
    # Financeiro / Bancos
    "ITUB4.SA": "FINANCEIRO",
    "BBDC4.SA": "FINANCEIRO",
    "BBAS3.SA": "FINANCEIRO",
    "SANB11.SA": "FINANCEIRO",
    "B3SA3.SA": "FINANCEIRO",
    "IRBR3.SA": "SEGUROS",
    # Tecnologia
    "TOTVS3.SA": "TECNOLOGIA",
    "LWSA3.SA": "TECNOLOGIA",
    "INTB3.SA": "TECNOLOGIA",
    # Consumo / Varejo
    "MGLU3.SA": "VAREJO",
    "VIIA3.SA": "VAREJO",
    "RENT3.SA": "LOCACAO",
    "LREN3.SA": "VAREJO",
    # Saúde
    "RDRD3.SA": "SAUDE",
    "HAPV3.SA": "SAUDE",
    "FLRY3.SA": "SAUDE",
    # Telecom / Utilities
    "VIVT3.SA": "TELECOM",
    "TIMS3.SA": "TELECOM",
    "ELET3.SA": "UTILITIES",
    "ELET6.SA": "UTILITIES",
    "CPFE3.SA": "UTILITIES",
    "SBSP3.SA": "UTILITIES",
    # Agro
    "AGRO3.SA": "AGRONEGOCIO",
    "SLCE3.SA": "AGRONEGOCIO",
    # === NYSE / NASDAQ - EUA ===
    # Tecnologia
    "AAPL": "TECNOLOGIA",
    "MSFT": "TECNOLOGIA",
    "NVDA": "TECNOLOGIA",
    "GOOGL": "TECNOLOGIA",
    "META": "TECNOLOGIA",
    "AMZN": "TECNOLOGIA",
    "TSLA": "TECNOLOGIA",
    "AMD": "TECNOLOGIA",
    "INTC": "TECNOLOGIA",
    "CRM": "TECNOLOGIA",
    # Financeiro
    "JPM": "FINANCEIRO",
    "BAC": "FINANCEIRO",
    "GS": "FINANCEIRO",
    "MS": "FINANCEIRO",
    "BRK-B": "FINANCEIRO",
    # Energia
    "XOM": "ENERGIA",
    "CVX": "ENERGIA",
    # Saúde
    "JNJ": "SAUDE",
    "UNH": "SAUDE",
    "PFE": "SAUDE",
    # Consumo
    "WMT": "VAREJO",
    "COST": "VAREJO",
    "MCD": "CONSUMO",
    "KO": "CONSUMO",
    # === CRIPTO (Top 10) ===
    "BTC-USD": "CRYPTO",
    "ETH-USD": "CRYPTO",
    "BNB-USD": "CRYPTO",
    "SOL-USD": "CRYPTO",
    "XRP-USD": "CRYPTO",
    "DOGE-USD": "CRYPTO",
    "ADA-USD": "CRYPTO",
    "AVAX-USD": "CRYPTO",
    "TRX-USD": "CRYPTO",
    "TON-USD": "CRYPTO",
}

TICKERS = [
    "PETR4.SA",
    "PETR3.SA",
    "PRIO3.SA",
    "UGPA3.SA",
    "VALE3.SA",
    "CSNA3.SA",
    "GGBR4.SA",
    "ITUB4.SA",
    "BBDC4.SA",
    "BBAS3.SA",
    "SANB11.SA",
    "B3SA3.SA",
    "IRBR3.SA",
    "TOTVS3.SA",
    "LWSA3.SA",
    "INTB3.SA",
    "MGLU3.SA",
    "VIIA3.SA",
    "RENT3.SA",
    "LREN3.SA",
    "RDRD3.SA",
    "HAPV3.SA",
    "FLRY3.SA",
    "VIVT3.SA",
    "TIMS3.SA",
    "ELET3.SA",
    "ELET6.SA",
    "CPFE3.SA",
    "SBSP3.SA",
    "AGRO3.SA",
    "SLCE3.SA",
    "AAPL",
    "MSFT",
    "NVDA",
    "GOOGL",
    "META",
    "AMZN",
    "TSLA",
    "AMD",
    "INTC",
    "CRM",
    "JPM",
    "BAC",
    "GS",
    "MS",
    "BRK-B",
    "XOM",
    "CVX",
    "JNJ",
    "UNH",
    "PFE",
    "WMT",
    "COST",
    "MCD",
    "KO",
    "BTC-USD",
    "ETH-USD",
    "BNB-USD",
    "SOL-USD",
    "XRP-USD",
    "DOGE-USD",
    "ADA-USD",
    "AVAX-USD",
    "TRX-USD",
    "TON-USD",
]

SECTORS = [
    "ENERGIA",
    "MINERACAO",
    "SIDERURGIA",
    "PAPEL_CELULOSE",
    "FINANCEIRO",
    "SEGUROS",
    "TECNOLOGIA",
    "LOCACAO",
    "VAREJO",
    "SAUDE",
    "TELECOM",
    "UTILITIES",
    "AGRONEGOCIO",
    "CONSUMO",
    "CRYPTO",
]

